modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="gtceu"
mandatory=true
versionRange="[${gtceu_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "storagedrawers"
mandatory = true
versionRange = "[12.5,13)"
ordering = "AFTER"
side = "BOTH"
